name: riaf
channels:
  - conda-forge
dependencies:
  - ipython
  - pip
  - numpy
  - pandas
  - python=3.11.9
  - pip:
      - arxiv==1.4.8
      - azure-core
      - azure-identity
      - beautifulsoup4
      - biopython==1.84
      - docx2txt==0.8
      - docxtpl==0.18.0
      - langchain-text-splitters
      - langfuse
      - llama-index==0.10.56
      - llama-index-core==0.10.56
      - llama-index-embeddings-azure-openai==0.1.11
      - llama-index-embeddings-openai==0.1.11
      - llama-index-llms-azure-openai==0.1.9
      - llama-index-readers-file==0.1.30
      - llama-index-readers-web==0.1.23
      - openai==1.36.1
      - pymupdf
      - pypdf
      - pypdf2
      - pyyaml
      - requests
      - semanticscholar==0.8.4
      - streamlit==1.36
      - trafilatura==1.11.0

