name: fmh2
channels:
  - conda-forge
dependencies:
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - ipython=8.26.0
  - jedi=0.19.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=18.1.8
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.27
  - libsqlite=3.46.0
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - openssl=3.3.1
  - pandas=2.2.2
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.0
  - prompt-toolkit=3.0.47
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - readline=8.2
  - setuptools=71.0.4
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - traitlets=5.14.3
  - tzdata=2024a
  - wcwidth=0.2.13
  - wheel=0.43.0
  - xz=5.2.6
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - altair==5.3.0
      - annotated-types==0.7.0
      - anyio==4.4.0
      - arxiv==1.4.8
      - attrs==23.2.0
      - azure-core==1.30.2
      - azure-identity==1.17.1
      - babel==2.15.0
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - biopython==1.84
      - blinker==1.8.2
      - cachetools==5.4.0
      - certifi==2024.7.4
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - chromedriver-autoinstaller==0.6.4
      - click==8.1.7
      - courlan==1.2.0
      - cryptography==43.0.0
      - cssselect==1.2.0
      - dataclasses-json==0.6.7
      - dateparser==1.2.0
      - deprecated==1.2.14
      - dirtyjson==1.0.8
      - distro==1.9.0
      - docx2txt==0.8
      - docxcompose==1.4.0
      - docxtpl==0.18.0
      - feedfinder2==0.0.4
      - feedparser==6.0.11
      - filelock==3.15.4
      - frozenlist==1.4.1
      - fsspec==2024.6.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - h11==0.14.0
      - html2text==2024.2.26
      - htmldate==1.8.1
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - jieba3k==0.35.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - justext==3.0.1
      - langchain-core==0.2.22
      - langchain-text-splitters==0.2.2
      - langfuse==2.39.2
      - langsmith==0.1.93
      - llama-cloud==0.0.9
      - llama-index==0.10.56
      - llama-index-agent-openai==0.2.9
      - llama-index-cli==0.1.12
      - llama-index-core==0.10.56
      - llama-index-embeddings-azure-openai==0.1.11
      - llama-index-embeddings-openai==0.1.11
      - llama-index-indices-managed-llama-cloud==0.2.5
      - llama-index-legacy==0.9.48
      - llama-index-llms-azure-openai==0.1.9
      - llama-index-llms-openai==0.1.26
      - llama-index-multi-modal-llms-openai==0.1.8
      - llama-index-program-openai==0.1.6
      - llama-index-question-gen-openai==0.1.3
      - llama-index-readers-file==0.1.30
      - llama-index-readers-llama-parse==0.1.6
      - llama-index-readers-web==0.1.23
      - llama-parse==0.4.9
      - lxml==5.2.2
      - lxml-html-clean==0.1.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.21.3
      - mdurl==0.1.2
      - msal==1.30.0
      - msal-extensions==1.2.0
      - multidict==6.0.5
      - mypy-extensions==1.0.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - newspaper3k==0.2.8
      - nltk==3.8.1
      - numpy==1.26.4
      - openai==1.36.1
      - orjson==3.10.6
      - outcome==1.3.0.post0
      - packaging==23.2
      - pillow==10.4.0
      - playwright==1.45.0
      - portalocker==2.10.1
      - protobuf==5.27.2
      - pyarrow==17.0.0
      - pycparser==2.22
      - pydantic==2.8.2
      - pydantic-core==2.20.1
      - pydeck==0.9.1
      - pyee==11.1.0
      - pyjwt==2.8.0
      - pymupdf==1.24.7
      - pymupdfb==1.24.6
      - pypdf==4.3.1
      - pypdf2==3.0.1
      - pysocks==1.7.1
      - python-docx==1.1.2
      - pyyaml==6.0.1
      - referencing==0.35.1
      - regex==2024.5.15
      - requests==2.32.3
      - requests-file==2.1.0
      - rich==13.7.1
      - rpds-py==0.19.0
      - selenium==4.23.0
      - semanticscholar==0.8.4
      - sgmllib3k==1.0.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spider-client==0.0.27
      - sqlalchemy==2.0.31
      - streamlit==1.36.0
      - striprtf==0.0.26
      - tenacity==8.5.0
      - tiktoken==0.7.0
      - tinysegmenter==0.3
      - tld==0.13
      - tldextract==5.1.2
      - toml==0.10.2
      - toolz==0.12.1
      - tornado==6.4.1
      - tqdm==4.66.4
      - trafilatura==1.11.0
      - trio==0.26.0
      - trio-websocket==0.11.1
      - typing-extensions==4.9.0
      - typing-inspect==0.9.0
      - tzlocal==5.2
      - urllib3==2.2.2
      - websocket-client==1.8.0
      - wrapt==1.16.0
      - wsproto==1.2.0
      - yarl==1.9.4
