name: ragpipe
channels:
  - conda-forge
dependencies:
  - aiohttp=3.9.1
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=3.7.1
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - attrs=23.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - cachetools=5.3.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - cryptography=41.0.7
  - dataclasses-json=0.6.3
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - frozenlist=1.4.1
  - idna=3.6
  - iniconfig=2.0.0
  - ipython=8.18.1
  - jedi=0.19.1
  - jsonpatch=1.33
  - jsonpointer=2.4
  - langchain-community=0.0.2
  - langchain-core=0.1.2
  - langsmith=0.0.72
  - libabseil=20230802.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=16.0.6
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - liblapack=3.9.0
  - libopenblas=0.3.25
  - libprotobuf=4.24.4
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - marshmallow=3.20.1
  - matplotlib-inline=0.1.6
  - multidict=6.0.4
  - mypy_extensions=1.0.0
  - ncurses=6.4
  - numexpr=2.8.7
  - numpy=1.26.2
  - openapi-schema-pydantic=1.2.4
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pluggy=1.3.0
  - prompt-toolkit=3.0.41
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.5.1
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pydantic=2.5.2
  - pydantic-core=2.14.5
  - pygments=2.17.2
  - pyopenssl=23.3.0
  - pysocks=1.7.1
  - pytest=7.4.3
  - pytest-subtests=0.11.0
  - python=3.10.13
  - python_abi=3.10
  - pyu2f=0.1.5
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - rsa=4.9
  - setuptools=68.2.2
  - six=1.16.0
  - sniffio=1.3.0
  - sqlalchemy=2.0.23
  - stack_data=0.6.2
  - tenacity=8.2.3
  - tk=8.6.13
  - tomli=2.0.1
  - traitlets=5.14.0
  - typing_inspect=0.9.0
  - urllib3=2.1.0
  - wcwidth=0.2.12
  - wheel=0.42.0
  - xz=5.2.6
  - yaml=0.2.5
  - pip:
      - adal==1.2.7
      - aiofiles==23.2.1
      - aniso8601==9.0.1
      - applicationinsights==0.11.10
      - appnope==0.1.3
      - argcomplete==3.1.6
      - arxiv==2.1.0
      - asgiref==3.7.2
      - backoff==2.2.1
      - backports-tempfile==1.0
      - backports-weakref==1.0.post1
      - bcrypt==4.1.1
      - beautifulsoup4==4.12.3
      - blinker==1.7.0
      - blis==0.7.11
      - bs4==0.0.2
      - catalogue==2.0.10
      - chardet==5.2.0
      - chromedriver-autoinstaller==0.6.4
      - click==8.1.7
      - cloudpathlib==0.16.0
      - cloudpickle==2.2.1
      - coloredlogs==15.0.1
      - comm==0.2.0
      - commonmark==0.9.1
      - confection==0.1.4
      - contextlib2==21.6.0
      - contourpy==1.2.0
      - crossref-commons==0.0.7
      - cssselect==1.2.0
      - cssselect2==0.7.0
      - curl-cffi==0.5.10
      - cycler==0.12.1
      - cymem==2.0.8
      - databricks-cli==0.18.0
      - dataclasses-json-speakeasy==0.5.11
      - debugpy==1.8.0
      - deprecated==1.2.14
      - dirtyjson==1.0.8
      - diskcache==5.6.3
      - distro==1.8.0
      - dnspython==2.4.2
      - docker==6.1.3
      - docopt==0.6.2
      - docutils==0.20.1
      - duckduckgo-search==4.2
      - emoji==2.10.1
      - entrypoints==0.4
      - feedfinder2==0.0.4
      - feedparser==6.0.10
      - filelock==3.13.1
      - filetype==1.2.0
      - flask==3.0.2
      - flask-restx==1.3.0
      - fonttools==4.47.2
      - fsspec==2023.12.2
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-api-core==2.14.0
      - google-auth==2.24.0
      - google-search-results==2.4.1
      - googleapis-common-protos==1.61.0
      - gptcache==0.1.43
      - greenlet==3.0.3
      - guidance==0.0.64
      - h11==0.14.0
      - html2text==2020.1.16
      - html5lib==1.1
      - httpcore==1.0.2
      - httpx==0.26.0
      - humanfriendly==10.0
      - importlib-metadata==6.11.0
      - importlib-resources==6.1.1
      - interegular==0.3.3
      - ipykernel==6.27.1
      - isodate==0.6.1
      - itsdangerous==2.1.2
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - jieba3k==0.35.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonpath-ng==1.6.1
      - jsonpath-python==1.0.6
      - jsonpickle==3.0.2
      - jsonschema==4.20.0
      - jsonschema-path==0.3.2
      - jsonschema-spec==0.2.4
      - jsonschema-specifications==2023.7.1
      - jupyter-client==8.6.0
      - jupyter-core==5.5.1
      - keyring==24.3.0
      - kiwisolver==1.4.5
      - knack==0.11.0
      - langchain==0.0.324
      - langcodes==3.3.0
      - langdetect==1.0.9
      - lazy-object-proxy==1.10.0
      - libmagic==1.0
      - llama-hub==0.0.71
      - llama-index==0.9.30
      - llama-index-core==0.10.3
      - llama-index-readers-web==0.1.2
      - lm-format-enforcer==0.4.3
      - loguru==0.7.2
      - lxml==5.1.0
      - markdown==3.5.2
      - markdown2==2.4.12
      - markupsafe==2.1.3
      - matplotlib==3.8.3
      - mdpdf==0.0.18
      - mlflow-skinny==2.8.1
      - more-itertools==10.1.0
      - motor==3.3.2
      - msal==1.25.0
      - msal-extensions==1.0.0
      - msrest==0.7.1
      - msrestazure==0.6.4
      - murmurhash==1.0.10
      - ndg-httpsclient==0.5.1
      - nest-asyncio==1.5.8
      - networkx==3.2.1
      - newspaper3k==0.2.8
      - nltk==3.8.1
      - oauthlib==3.2.2
      - openai==1.6.0
      - openapi-core==0.18.2
      - openapi-schema-validator==0.6.2
      - openapi-spec-validator==0.7.1
      - opencensus==0.11.3
      - opencensus-context==0.1.3
      - opencensus-ext-azure==1.1.12
      - opentelemetry-api==1.22.0
      - opentelemetry-exporter-otlp-proto-common==1.22.0
      - opentelemetry-exporter-otlp-proto-http==1.22.0
      - opentelemetry-proto==1.22.0
      - opentelemetry-sdk==1.22.0
      - opentelemetry-semantic-conventions==0.43b0
      - outcome==1.3.0.post0
      - pandas==2.1.4
      - paramiko==3.3.1
      - parse==1.20.0
      - pathable==0.4.3
      - pathspec==0.11.2
      - pillow==10.2.0
      - pkginfo==1.9.6
      - platformdirs==4.1.0
      - playwright==1.41.2
      - ply==3.11
      - portalocker==2.8.2
      - prance==23.6.21.0
      - preshed==3.0.9
      - promptflow==1.5.0
      - promptflow-tools==1.1.0
      - protobuf==4.25.1
      - psutil==5.9.6
      - pyaml==23.12.0
      - pyarrow==14.0.2
      - pybliometrics==3.6
      - pydash==7.0.5
      - pydyf==0.8.0
      - pyee==11.0.1
      - pygtrie==2.5.0
      - pyjwt==2.8.0
      - pylibmagic==0.5.0
      - pymongo==4.6.1
      - pymupdf==1.23.15
      - pymupdfb==1.23.9
      - pynacl==1.5.0
      - pyparsing==3.1.1
      - pypdf==3.17.4
      - pypdf2==3.0.1
      - pyphen==0.14.0
      - pyscihub==0.1.2
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - python-iso639==2024.2.7
      - python-magic==0.4.27
      - pytz==2023.3.post1
      - pyzmq==25.1.2
      - rank-bm25==0.2.2
      - rapidfuzz==3.6.1
      - ratelimit==2.2.1
      - referencing==0.30.2
      - regex==2023.10.3
      - requests-file==2.0.0
      - requests-oauthlib==1.3.1
      - retrying==1.3.4
      - rfc3339-validator==0.1.4
      - rpds-py==0.13.2
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - sci-hub==1.0.4
      - scidownl==1.0.2
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - secretstorage==3.3.3
      - selenium==4.17.2
      - semantic-kernel==0.4.3.dev0
      - semanticscholar==0.7.0
      - sgmllib3k==1.0.0
      - simple-loggers==1.0.5
      - smart-open==6.4.0
      - smmap==5.0.1
      - sortedcontainers==2.4.0
      - soupsieve==2.5
      - spacy==3.7.2
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlparse==0.4.4
      - srsly==2.4.8
      - strictyaml==1.7.3
      - tablib==3.5.0
      - tabulate==0.9.0
      - thinc==8.2.2
      - threadpoolctl==3.2.0
      - tiktoken==0.5.2
      - tinycss2==1.2.1
      - tinysegmenter==0.3
      - tldextract==5.1.1
      - tornado==6.4
      - tqdm==4.66.1
      - trio==0.24.0
      - trio-websocket==0.11.1
      - typer==0.9.0
      - typing-extensions==4.9.0
      - tzdata==2023.4
      - unstructured==0.12.4
      - unstructured-client==0.18.0
      - waitress==2.1.2
      - wasabi==1.1.2
      - weasel==0.3.4
      - webencodings==0.5.1
      - webrequests==1.0.8
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - wget==3.2
      - wrapt==1.16.0
      - wsproto==1.2.0
      - yarl==1.9.4
      - zipp==3.17.0
      - zopfli==0.2.3
